
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import ScrollToTopComponent from "@/components/common/ScrollToTop/ScrollToTop";

import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <body
        className={`${inter.className} antialiased`}
      >
        <Navbar/>
        {children}
        <ToastContainer />
        <Footer/>
        <ScrollToTopComponent/>
      </body>
    </html>
  );
}
